/**
 * Generated by `pnpm --filter @qavio/database db:generate-types` against
 * the real Supabase project (ref bkxkwwocpampseojowxs). Do not hand-edit
 * — re-run that command after any migration under supabase/migrations
 * and commit the result.
 *
 * This does include Row/Insert/Update shapes for `credential_secrets`
 * and `integration_account_secrets` (Supabase generates types from the
 * schema, not from RLS policies), but application code must never query
 * either table directly — both have zero RLS policies by design, so any
 * such query fails for every role except `service_role`. The only
 * sanctioned access path is `get_credential_secret()` /
 * `get_integration_access_token()` (see supabase/migrations).
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      ai_analyses: {
        Row: {
          completion_tokens: number | null
          created_at: string
          id: string
          issue_id: string | null
          model: string
          organization_id: string
          prompt_tokens: number | null
          provider: string
          raw_response: Json | null
          summary: string
          test_result_id: string | null
        }
        Insert: {
          completion_tokens?: number | null
          created_at?: string
          id?: string
          issue_id?: string | null
          model: string
          organization_id: string
          prompt_tokens?: number | null
          provider: string
          raw_response?: Json | null
          summary: string
          test_result_id?: string | null
        }
        Update: {
          completion_tokens?: number | null
          created_at?: string
          id?: string
          issue_id?: string | null
          model?: string
          organization_id?: string
          prompt_tokens?: number | null
          provider?: string
          raw_response?: Json | null
          summary?: string
          test_result_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ai_analyses_issue_id_fkey"
            columns: ["issue_id"]
            isOneToOne: false
            referencedRelation: "issues"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_analyses_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_analyses_test_result_id_fkey"
            columns: ["test_result_id"]
            isOneToOne: false
            referencedRelation: "test_results"
            referencedColumns: ["id"]
          },
        ]
      }
      artifacts: {
        Row: {
          checksum: string | null
          content_type: string | null
          created_at: string
          id: string
          kind: Database["public"]["Enums"]["artifact_kind"]
          organization_id: string
          size_bytes: number | null
          storage_bucket: string
          storage_path: string
          test_result_id: string
        }
        Insert: {
          checksum?: string | null
          content_type?: string | null
          created_at?: string
          id?: string
          kind: Database["public"]["Enums"]["artifact_kind"]
          organization_id: string
          size_bytes?: number | null
          storage_bucket?: string
          storage_path: string
          test_result_id: string
        }
        Update: {
          checksum?: string | null
          content_type?: string | null
          created_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["artifact_kind"]
          organization_id?: string
          size_bytes?: number | null
          storage_bucket?: string
          storage_path?: string
          test_result_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "artifacts_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "artifacts_test_result_id_fkey"
            columns: ["test_result_id"]
            isOneToOne: false
            referencedRelation: "test_results"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: string
          ip_address: unknown
          metadata: Json
          organization_id: string
          target_id: string | null
          target_type: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: string
          ip_address?: unknown
          metadata?: Json
          organization_id: string
          target_id?: string | null
          target_type?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: string
          ip_address?: unknown
          metadata?: Json
          organization_id?: string
          target_id?: string | null
          target_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_logs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      credential_secrets: {
        Row: {
          created_at: string
          credential_id: string
          vault_secret_id: string
        }
        Insert: {
          created_at?: string
          credential_id: string
          vault_secret_id: string
        }
        Update: {
          created_at?: string
          credential_id?: string
          vault_secret_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "credential_secrets_credential_id_fkey"
            columns: ["credential_id"]
            isOneToOne: true
            referencedRelation: "credentials"
            referencedColumns: ["id"]
          },
        ]
      }
      credentials: {
        Row: {
          created_at: string
          created_by: string | null
          environment_id: string | null
          id: string
          name: string
          organization_id: string
          project_id: string
          rotated_at: string | null
          type: Database["public"]["Enums"]["credential_type"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          environment_id?: string | null
          id?: string
          name: string
          organization_id: string
          project_id: string
          rotated_at?: string | null
          type?: Database["public"]["Enums"]["credential_type"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          environment_id?: string | null
          id?: string
          name?: string
          organization_id?: string
          project_id?: string
          rotated_at?: string | null
          type?: Database["public"]["Enums"]["credential_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "credentials_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "credentials_environment_id_fkey"
            columns: ["environment_id"]
            isOneToOne: false
            referencedRelation: "environments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "credentials_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "credentials_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      environments: {
        Row: {
          archived_at: string | null
          auth_credential_id: string | null
          auth_method: Database["public"]["Enums"]["environment_auth_method"]
          base_url: string
          configuration: Json
          created_at: string
          created_by: string | null
          id: string
          is_default: boolean
          kind: Database["public"]["Enums"]["environment_kind"]
          name: string
          organization_id: string
          project_id: string
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          auth_credential_id?: string | null
          auth_method?: Database["public"]["Enums"]["environment_auth_method"]
          base_url: string
          configuration?: Json
          created_at?: string
          created_by?: string | null
          id?: string
          is_default?: boolean
          kind?: Database["public"]["Enums"]["environment_kind"]
          name: string
          organization_id: string
          project_id: string
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          auth_credential_id?: string | null
          auth_method?: Database["public"]["Enums"]["environment_auth_method"]
          base_url?: string
          configuration?: Json
          created_at?: string
          created_by?: string | null
          id?: string
          is_default?: boolean
          kind?: Database["public"]["Enums"]["environment_kind"]
          name?: string
          organization_id?: string
          project_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "environments_auth_credential_id_fkey"
            columns: ["auth_credential_id"]
            isOneToOne: false
            referencedRelation: "credentials"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "environments_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "environments_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "environments_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      fix_attempts: {
        Row: {
          created_at: string
          finished_at: string | null
          fix_suggestion_id: string
          id: string
          log: string | null
          organization_id: string
          pull_request_url: string | null
          started_at: string | null
          status: Database["public"]["Enums"]["fix_attempt_status"]
        }
        Insert: {
          created_at?: string
          finished_at?: string | null
          fix_suggestion_id: string
          id?: string
          log?: string | null
          organization_id: string
          pull_request_url?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["fix_attempt_status"]
        }
        Update: {
          created_at?: string
          finished_at?: string | null
          fix_suggestion_id?: string
          id?: string
          log?: string | null
          organization_id?: string
          pull_request_url?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["fix_attempt_status"]
        }
        Relationships: [
          {
            foreignKeyName: "fix_attempts_fix_suggestion_id_fkey"
            columns: ["fix_suggestion_id"]
            isOneToOne: false
            referencedRelation: "fix_suggestions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fix_attempts_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      fix_suggestions: {
        Row: {
          ai_analysis_id: string | null
          approved_at: string | null
          approved_by: string | null
          created_at: string
          description: string
          diff: string | null
          id: string
          issue_id: string
          organization_id: string
          status: Database["public"]["Enums"]["fix_suggestion_status"]
          updated_at: string
        }
        Insert: {
          ai_analysis_id?: string | null
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string
          description: string
          diff?: string | null
          id?: string
          issue_id: string
          organization_id: string
          status?: Database["public"]["Enums"]["fix_suggestion_status"]
          updated_at?: string
        }
        Update: {
          ai_analysis_id?: string | null
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string
          description?: string
          diff?: string | null
          id?: string
          issue_id?: string
          organization_id?: string
          status?: Database["public"]["Enums"]["fix_suggestion_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "fix_suggestions_ai_analysis_id_fkey"
            columns: ["ai_analysis_id"]
            isOneToOne: false
            referencedRelation: "ai_analyses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fix_suggestions_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fix_suggestions_issue_id_fkey"
            columns: ["issue_id"]
            isOneToOne: false
            referencedRelation: "issues"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fix_suggestions_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      integration_account_secrets: {
        Row: {
          access_token_secret_id: string
          created_at: string
          integration_account_id: string
          refresh_token_secret_id: string | null
        }
        Insert: {
          access_token_secret_id: string
          created_at?: string
          integration_account_id: string
          refresh_token_secret_id?: string | null
        }
        Update: {
          access_token_secret_id?: string
          created_at?: string
          integration_account_id?: string
          refresh_token_secret_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "integration_account_secrets_integration_account_id_fkey"
            columns: ["integration_account_id"]
            isOneToOne: true
            referencedRelation: "integration_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      integration_accounts: {
        Row: {
          created_at: string
          expires_at: string | null
          external_account_id: string
          external_account_name: string | null
          id: string
          integration_id: string
          organization_id: string
          scope: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          expires_at?: string | null
          external_account_id: string
          external_account_name?: string | null
          id?: string
          integration_id: string
          organization_id: string
          scope?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          expires_at?: string | null
          external_account_id?: string
          external_account_name?: string | null
          id?: string
          integration_id?: string
          organization_id?: string
          scope?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "integration_accounts_integration_id_fkey"
            columns: ["integration_id"]
            isOneToOne: false
            referencedRelation: "integrations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "integration_accounts_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      integrations: {
        Row: {
          config: Json
          connected_at: string | null
          connected_by: string | null
          created_at: string
          id: string
          is_connected: boolean
          organization_id: string
          provider: Database["public"]["Enums"]["integration_provider"]
          updated_at: string
        }
        Insert: {
          config?: Json
          connected_at?: string | null
          connected_by?: string | null
          created_at?: string
          id?: string
          is_connected?: boolean
          organization_id: string
          provider: Database["public"]["Enums"]["integration_provider"]
          updated_at?: string
        }
        Update: {
          config?: Json
          connected_at?: string | null
          connected_by?: string | null
          created_at?: string
          id?: string
          is_connected?: boolean
          organization_id?: string
          provider?: Database["public"]["Enums"]["integration_provider"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "integrations_connected_by_fkey"
            columns: ["connected_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "integrations_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      invitations: {
        Row: {
          accepted_at: string | null
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by: string | null
          organization_id: string
          role: Database["public"]["Enums"]["organization_role"]
          status: Database["public"]["Enums"]["invitation_status"]
          token: string
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          email: string
          expires_at?: string
          id?: string
          invited_by?: string | null
          organization_id: string
          role?: Database["public"]["Enums"]["organization_role"]
          status?: Database["public"]["Enums"]["invitation_status"]
          token?: string
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string | null
          organization_id?: string
          role?: Database["public"]["Enums"]["organization_role"]
          status?: Database["public"]["Enums"]["invitation_status"]
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "invitations_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invitations_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      issue_comments: {
        Row: {
          author_id: string | null
          body: string
          created_at: string
          id: string
          issue_id: string
          organization_id: string
          updated_at: string
        }
        Insert: {
          author_id?: string | null
          body: string
          created_at?: string
          id?: string
          issue_id: string
          organization_id: string
          updated_at?: string
        }
        Update: {
          author_id?: string | null
          body?: string
          created_at?: string
          id?: string
          issue_id?: string
          organization_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "issue_comments_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "issue_comments_issue_id_fkey"
            columns: ["issue_id"]
            isOneToOne: false
            referencedRelation: "issues"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "issue_comments_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      issues: {
        Row: {
          ai_summary: string | null
          assigned_to: string | null
          created_at: string
          created_by: string | null
          description: string | null
          evidence: Json
          external_issue_url: string | null
          id: string
          organization_id: string
          project_id: string
          severity: Database["public"]["Enums"]["issue_severity"]
          status: Database["public"]["Enums"]["issue_status"]
          test_result_id: string | null
          test_run_id: string | null
          title: string
          updated_at: string
        }
        Insert: {
          ai_summary?: string | null
          assigned_to?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          evidence?: Json
          external_issue_url?: string | null
          id?: string
          organization_id: string
          project_id: string
          severity?: Database["public"]["Enums"]["issue_severity"]
          status?: Database["public"]["Enums"]["issue_status"]
          test_result_id?: string | null
          test_run_id?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          ai_summary?: string | null
          assigned_to?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          evidence?: Json
          external_issue_url?: string | null
          id?: string
          organization_id?: string
          project_id?: string
          severity?: Database["public"]["Enums"]["issue_severity"]
          status?: Database["public"]["Enums"]["issue_status"]
          test_result_id?: string | null
          test_run_id?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "issues_assigned_to_fkey"
            columns: ["assigned_to"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "issues_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "issues_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "issues_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "issues_test_result_id_fkey"
            columns: ["test_result_id"]
            isOneToOne: false
            referencedRelation: "test_results"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "issues_test_run_id_fkey"
            columns: ["test_run_id"]
            isOneToOne: false
            referencedRelation: "test_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          id: string
          metadata: Json
          organization_id: string
          read_at: string | null
          title: string
          type: string
          user_id: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          organization_id: string
          read_at?: string | null
          title: string
          type: string
          user_id: string
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          organization_id?: string
          read_at?: string | null
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      organization_members: {
        Row: {
          created_at: string
          id: string
          invited_by: string | null
          organization_id: string
          role: Database["public"]["Enums"]["organization_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          invited_by?: string | null
          organization_id: string
          role?: Database["public"]["Enums"]["organization_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          invited_by?: string | null
          organization_id?: string
          role?: Database["public"]["Enums"]["organization_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "organization_members_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "organization_members_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "organization_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          name: string
          slug: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          name: string
          slug: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          name?: string
          slug?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "organizations_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          full_name: string | null
          id: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          full_name?: string | null
          id: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          full_name?: string | null
          id?: string
          updated_at?: string
        }
        Relationships: []
      }
      projects: {
        Row: {
          archived_at: string | null
          created_at: string
          created_by: string | null
          description: string | null
          id: string
          name: string
          organization_id: string
          platform: Database["public"]["Enums"]["project_platform"]
          slug: string
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          name: string
          organization_id: string
          platform?: Database["public"]["Enums"]["project_platform"]
          slug: string
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          name?: string
          organization_id?: string
          platform?: Database["public"]["Enums"]["project_platform"]
          slug?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "projects_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "projects_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      subscriptions: {
        Row: {
          created_at: string
          current_period_end: string | null
          current_period_start: string | null
          id: string
          organization_id: string
          plan: string
          provider: string | null
          provider_subscription_id: string | null
          seats: number
          status: Database["public"]["Enums"]["subscription_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          organization_id: string
          plan?: string
          provider?: string | null
          provider_subscription_id?: string | null
          seats?: number
          status?: Database["public"]["Enums"]["subscription_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          organization_id?: string
          plan?: string
          provider?: string | null
          provider_subscription_id?: string | null
          seats?: number
          status?: Database["public"]["Enums"]["subscription_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: true
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      test_cases: {
        Row: {
          created_at: string
          created_by: string | null
          description: string | null
          expected_result: string | null
          id: string
          is_active: boolean
          organization_id: string
          priority: string
          project_id: string
          steps: Json
          tags: string[]
          test_suite_id: string
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          expected_result?: string | null
          id?: string
          is_active?: boolean
          organization_id: string
          priority?: string
          project_id: string
          steps?: Json
          tags?: string[]
          test_suite_id: string
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          expected_result?: string | null
          id?: string
          is_active?: boolean
          organization_id?: string
          priority?: string
          project_id?: string
          steps?: Json
          tags?: string[]
          test_suite_id?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "test_cases_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_cases_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_cases_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_cases_test_suite_id_fkey"
            columns: ["test_suite_id"]
            isOneToOne: false
            referencedRelation: "test_suites"
            referencedColumns: ["id"]
          },
        ]
      }
      test_results: {
        Row: {
          created_at: string
          duration_ms: number
          error_message: string | null
          id: string
          name: string
          organization_id: string
          status: Database["public"]["Enums"]["test_result_status"]
          test_case_id: string | null
          test_run_id: string
        }
        Insert: {
          created_at?: string
          duration_ms?: number
          error_message?: string | null
          id?: string
          name: string
          organization_id: string
          status: Database["public"]["Enums"]["test_result_status"]
          test_case_id?: string | null
          test_run_id: string
        }
        Update: {
          created_at?: string
          duration_ms?: number
          error_message?: string | null
          id?: string
          name?: string
          organization_id?: string
          status?: Database["public"]["Enums"]["test_result_status"]
          test_case_id?: string | null
          test_run_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "test_results_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_results_test_case_id_fkey"
            columns: ["test_case_id"]
            isOneToOne: false
            referencedRelation: "test_cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_results_test_run_id_fkey"
            columns: ["test_run_id"]
            isOneToOne: false
            referencedRelation: "test_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      test_run_jobs: {
        Row: {
          attempts: number
          created_at: string
          finished_at: string | null
          id: string
          job_id: string
          last_error: string | null
          organization_id: string
          queue_name: string
          started_at: string | null
          status: Database["public"]["Enums"]["test_run_job_status"]
          test_run_id: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          finished_at?: string | null
          id?: string
          job_id: string
          last_error?: string | null
          organization_id: string
          queue_name: string
          started_at?: string | null
          status?: Database["public"]["Enums"]["test_run_job_status"]
          test_run_id: string
        }
        Update: {
          attempts?: number
          created_at?: string
          finished_at?: string | null
          id?: string
          job_id?: string
          last_error?: string | null
          organization_id?: string
          queue_name?: string
          started_at?: string | null
          status?: Database["public"]["Enums"]["test_run_job_status"]
          test_run_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "test_run_jobs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_run_jobs_test_run_id_fkey"
            columns: ["test_run_id"]
            isOneToOne: false
            referencedRelation: "test_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      test_runs: {
        Row: {
          configuration: Json
          created_at: string
          environment_id: string
          error_message: string | null
          finished_at: string | null
          id: string
          organization_id: string
          progress: string | null
          project_id: string
          started_at: string | null
          status: Database["public"]["Enums"]["test_run_status"]
          summary: Json
          test_suite_id: string | null
          triggered_by: string | null
          type: Database["public"]["Enums"]["test_run_type"]
        }
        Insert: {
          configuration?: Json
          created_at?: string
          environment_id: string
          error_message?: string | null
          finished_at?: string | null
          id?: string
          organization_id: string
          progress?: string | null
          project_id: string
          started_at?: string | null
          status?: Database["public"]["Enums"]["test_run_status"]
          summary?: Json
          test_suite_id?: string | null
          triggered_by?: string | null
          type?: Database["public"]["Enums"]["test_run_type"]
        }
        Update: {
          configuration?: Json
          created_at?: string
          environment_id?: string
          error_message?: string | null
          finished_at?: string | null
          id?: string
          organization_id?: string
          progress?: string | null
          project_id?: string
          started_at?: string | null
          status?: Database["public"]["Enums"]["test_run_status"]
          summary?: Json
          test_suite_id?: string | null
          triggered_by?: string | null
          type?: Database["public"]["Enums"]["test_run_type"]
        }
        Relationships: [
          {
            foreignKeyName: "test_runs_environment_id_fkey"
            columns: ["environment_id"]
            isOneToOne: false
            referencedRelation: "environments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_runs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_runs_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_runs_test_suite_id_fkey"
            columns: ["test_suite_id"]
            isOneToOne: false
            referencedRelation: "test_suites"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_runs_triggered_by_fkey"
            columns: ["triggered_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      test_suites: {
        Row: {
          created_at: string
          created_by: string | null
          description: string | null
          id: string
          name: string
          organization_id: string
          project_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          name: string
          organization_id: string
          project_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          name?: string
          organization_id?: string
          project_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "test_suites_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_suites_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_suites_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      usage_events: {
        Row: {
          created_at: string
          estimated_cost_cents: number | null
          event_type: string
          id: string
          metadata: Json
          model: string | null
          organization_id: string
          project_id: string | null
          provider: string | null
          quantity: number
          test_run_id: string | null
          unit: string
        }
        Insert: {
          created_at?: string
          estimated_cost_cents?: number | null
          event_type: string
          id?: string
          metadata?: Json
          model?: string | null
          organization_id: string
          project_id?: string | null
          provider?: string | null
          quantity: number
          test_run_id?: string | null
          unit: string
        }
        Update: {
          created_at?: string
          estimated_cost_cents?: number | null
          event_type?: string
          id?: string
          metadata?: Json
          model?: string | null
          organization_id?: string
          project_id?: string | null
          provider?: string | null
          quantity?: number
          test_run_id?: string | null
          unit?: string
        }
        Relationships: [
          {
            foreignKeyName: "usage_events_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "usage_events_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "usage_events_test_run_id_fkey"
            columns: ["test_run_id"]
            isOneToOne: false
            referencedRelation: "test_runs"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_invitation: {
        Args: { p_token: string }
        Returns: {
          created_at: string
          created_by: string | null
          id: string
          name: string
          slug: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "organizations"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      can_manage_test_workflows: {
        Args: { target_organization_id: string }
        Returns: boolean
      }
      create_credential_secret: {
        Args: { p_credential_id: string; p_secret: string }
        Returns: undefined
      }
      create_organization: {
        Args: { org_name: string; org_slug: string }
        Returns: {
          created_at: string
          created_by: string | null
          id: string
          name: string
          slug: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "organizations"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      get_credential_secret: {
        Args: { p_credential_id: string }
        Returns: string
      }
      get_integration_access_token: {
        Args: { p_integration_account_id: string }
        Returns: string
      }
      get_invitation_preview: {
        Args: { p_token: string }
        Returns: {
          email: string
          expires_at: string
          organization_name: string
          role: Database["public"]["Enums"]["organization_role"]
          status: Database["public"]["Enums"]["invitation_status"]
        }[]
      }
      has_organization_role: {
        Args: {
          min_role: Database["public"]["Enums"]["organization_role"]
          target_organization_id: string
        }
        Returns: boolean
      }
      is_organization_member: {
        Args: { target_organization_id: string }
        Returns: boolean
      }
      log_audit_event: {
        Args: {
          p_action: string
          p_metadata?: Json
          p_organization_id: string
          p_target_id?: string
          p_target_type?: string
        }
        Returns: {
          action: string
          actor_id: string | null
          created_at: string
          id: string
          ip_address: unknown
          metadata: Json
          organization_id: string
          target_id: string | null
          target_type: string | null
        }
        SetofOptions: {
          from: "*"
          to: "audit_logs"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      organization_role_rank: {
        Args: { role: Database["public"]["Enums"]["organization_role"] }
        Returns: number
      }
      set_default_environment: {
        Args: { p_environment_id: string }
        Returns: {
          archived_at: string | null
          auth_credential_id: string | null
          auth_method: Database["public"]["Enums"]["environment_auth_method"]
          base_url: string
          configuration: Json
          created_at: string
          created_by: string | null
          id: string
          is_default: boolean
          kind: Database["public"]["Enums"]["environment_kind"]
          name: string
          organization_id: string
          project_id: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "environments"
          isOneToOne: true
          isSetofReturn: false
        }
      }
    }
    Enums: {
      artifact_kind:
        | "screenshot"
        | "video"
        | "trace"
        | "log"
        | "dom_snapshot"
        | "json_report"
      credential_type:
        | "api_key"
        | "basic_auth"
        | "oauth_token"
        | "ssh_key"
        | "generic"
        | "playwright_storage_state"
        | "login_credentials"
      environment_auth_method: "none" | "stored_state" | "credentials"
      environment_kind: "production" | "staging" | "preview" | "local"
      fix_attempt_status: "pending" | "running" | "succeeded" | "failed"
      fix_suggestion_status: "proposed" | "approved" | "rejected" | "applied"
      integration_provider:
        | "jira"
        | "clickup"
        | "notion"
        | "linear"
        | "github"
        | "gitlab"
      invitation_status: "pending" | "accepted" | "revoked" | "expired"
      issue_severity: "critical" | "high" | "medium" | "low"
      issue_status:
        | "open"
        | "in_progress"
        | "resolved"
        | "reopened"
        | "ignored"
        | "duplicate"
      organization_role: "owner" | "admin" | "qa" | "developer" | "viewer"
      project_platform: "web" | "mobile" | "api"
      subscription_status: "trialing" | "active" | "past_due" | "canceled"
      test_result_status: "passed" | "failed" | "skipped" | "blocked"
      test_run_job_status:
        | "queued"
        | "active"
        | "completed"
        | "failed"
        | "delayed"
      test_run_status:
        | "created"
        | "queued"
        | "starting"
        | "running"
        | "analyzing"
        | "completed"
        | "failed"
        | "cancelled"
        | "blocked"
      test_run_type: "functional" | "visual" | "responsive" | "security"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      artifact_kind: [
        "screenshot",
        "video",
        "trace",
        "log",
        "dom_snapshot",
        "json_report",
      ],
      credential_type: [
        "api_key",
        "basic_auth",
        "oauth_token",
        "ssh_key",
        "generic",
        "playwright_storage_state",
        "login_credentials",
      ],
      environment_auth_method: ["none", "stored_state", "credentials"],
      environment_kind: ["production", "staging", "preview", "local"],
      fix_attempt_status: ["pending", "running", "succeeded", "failed"],
      fix_suggestion_status: ["proposed", "approved", "rejected", "applied"],
      integration_provider: [
        "jira",
        "clickup",
        "notion",
        "linear",
        "github",
        "gitlab",
      ],
      invitation_status: ["pending", "accepted", "revoked", "expired"],
      issue_severity: ["critical", "high", "medium", "low"],
      issue_status: [
        "open",
        "in_progress",
        "resolved",
        "reopened",
        "ignored",
        "duplicate",
      ],
      organization_role: ["owner", "admin", "qa", "developer", "viewer"],
      project_platform: ["web", "mobile", "api"],
      subscription_status: ["trialing", "active", "past_due", "canceled"],
      test_result_status: ["passed", "failed", "skipped", "blocked"],
      test_run_job_status: [
        "queued",
        "active",
        "completed",
        "failed",
        "delayed",
      ],
      test_run_status: [
        "created",
        "queued",
        "starting",
        "running",
        "analyzing",
        "completed",
        "failed",
        "cancelled",
        "blocked",
      ],
      test_run_type: ["functional", "visual", "responsive", "security"],
    },
  },
} as const
